In [31]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'customer_id': [1, 2, 3, 4, 2, 5],
    'age':         [25, np.nan, 35, np.nan, np.nan, 40],
    'city':        ['Mumbai', 'Delhi', np.nan, 'Mumbai', 'Delhi', np.nan],
    'gender':      ['Male', 'Female', 'Female', 'Male', 'Female', 'Male'],
    'annual_income': [40000, 80000, 60000, 120000, 80000, 95000]
})

In [32]:
df

   customer_id   age    city  gender  annual_income
0            1  25.0  Mumbai    Male          40000
1            2   NaN   Delhi  Female          80000
2            3  35.0     NaN  Female          60000
3            4   NaN  Mumbai    Male         120000
4            2   NaN   Delhi  Female          80000
5            5  40.0     NaN    Male          95000

In [33]:
medianAge = df['age'].median()
print(f"Medisan of age column: {medianAge}")
df['age'] = df['age'].fillna(medianAge)
print(f"df after filling empty age cells age cells with Median: \n{df}")

Medisan of age column: 35.0
df after filling empty age cells age cells with Median:
   customer_id   age    city  gender  annual_income
0            1  25.0  Mumbai    Male          40000
1            2  35.0   Delhi  Female          80000
2            3  35.0     NaN  Female          60000
3            4  35.0  Mumbai    Male         120000
4            2  35.0   Delhi  Female          80000
5            5  40.0     NaN    Male          95000

In [34]:
print(f"Total no.of duplicates present in dataset: {df.duplicated().sum()}")
df = df.drop_duplicates()

Total no.of duplicates present in dataset: 1

In [35]:
print(f"df after dropping duplicates: \n{df}")

df after dropping duplicates:
   customer_id   age    city  gender  annual_income
0            1  25.0  Mumbai    Male          40000
1            2  35.0   Delhi  Female          80000
2            3  35.0     NaN  Female          60000
3            4  35.0  Mumbai    Male         120000
5            5  40.0     NaN    Male          95000

In [36]:
#one-hot encoding to city
df = pd.get_dummies(df,columns=['city'],drop_first=False)
print(f"df after applying one-hot encoding to city: \n{df}")
print(f"shape of df after OHE: {df.shape}")

df after applying one-hot encoding to city:
   customer_id   age  gender  annual_income  city_Delhi  city_Mumbai
0            1  25.0    Male          40000       False         True
1            2  35.0  Female          80000        True        False
2            3  35.0  Female          60000       False        False
3            4  35.0    Male         120000       False         True
5            5  40.0    Male          95000       False        False
shape of df after OHE: (5, 6)

In [ ]:
#Label encoding for gender column
df['gender']=df['gender'].map({'Male':0,'Female':1})
df

   customer_id   age  gender  annual_income  city_Delhi  city_Mumbai
0            1  25.0       0          40000       False         True
1            2  35.0       1          80000        True        False
2            3  35.0       1          60000       False        False
3            4  35.0       0         120000       False         True
5            5  40.0       0          95000       False        False

In [38]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

scalar = StandardScaler()
minmax=MinMaxScaler()
numCols=['age','annual_income']
df_scalar = scalar.fit_transform(df[numCols])
print(f"scaled data using standard scalar: \n{df_scalar}")
df_minmax = minmax.fit_transform(df[numCols])
print(f"\nscaled data using minmax scalar: \n{df_minmax}")

'''Use Min-Max Scaling when you want values in a fixed range (like 0–1), especially for neural networks or distance-based algorithms without major outliers.
Use StandardScaler when the data is approximately normally distributed or when algorithms assume mean = 0 and standard deviation = 1 (e.g., SVM, Logistic Regression, PCA). '''

scaled data using standard scalar:
[[-1.83711731 -1.41097048]
 [ 0.20412415  0.03617873]
 [ 0.20412415 -0.68739588]
 [ 0.20412415  1.48332794]
 [ 1.22474487  0.57885968]]

scaled data using minmax scalar:
[[0.         0.        ]
 [0.66666667 0.5       ]
 [0.66666667 0.25      ]
 [0.66666667 1.        ]
 [1.         0.6875    ]]

'Use Min-Max Scaling when you want values in a fixed range (like 0–1), especially for neural networks or distance-based algorithms without major outliers.\nUse StandardScaler when the data is approximately normally distributed or when algorithms assume mean = 0 and standard deviation = 1 (e.g., SVM, Logistic Regression, PCA). '