In [32]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error

In [26]:
houseParams = {"area_sqft":[1200,1500,900,1800],
                "bedrooms":[3,4,2,4],
                 "age_years":[5,2,10,1], 
                 "price_lakhs":[45,65,30,80]}
houseData = pd.DataFrame(houseParams)
display(houseData)

   area_sqft  bedrooms  age_years  price_lakhs
0       1200         3          5           45
1       1500         4          2           65
2        900         2         10           30
3       1800         4          1           80

In [27]:
x = houseData[["area_sqft","bedrooms","age_years"]]
y = houseData[["price_lakhs"]]

display(x)
display(y)

   area_sqft  bedrooms  age_years
0       1200         3          5
1       1500         4          2
2        900         2         10
3       1800         4          1

   price_lakhs
0           45
1           65
2           30
3           80

In [28]:
xTrain,xTest,yTrain,yTest = train_test_split(x,y,random_state=0,test_size=0.25)

In [29]:
xTrain

   area_sqft  bedrooms  age_years
3       1800         4          1
1       1500         4          2
0       1200         3          5

In [30]:
scalar = StandardScaler()
numericCols=['area_sqft','bedrooms','age_years']
xTrain[numericCols]=scalar.fit_transform(xTrain[numericCols])
xTest[numericCols]=scalar.transform(xTest[numericCols])

In [31]:
housePredictionModel = LinearRegression()
housePredictionModel.fit(xTrain,yTrain)

print(f"House Prediction Model's coefficients::: \n{housePredictionModel.coef_}")
print(f"House Prediction Model's intercept::: \n{housePredictionModel.intercept_}")

House Prediction Model's coefficients:::
[[10.00208312 -0.23570226 -4.67410122]]
House Prediction Model's intercept:::
[63.33333333]

In [36]:
yTestPred = housePredictionModel.predict(xTest)

testMAE = mean_absolute_error(yTest,yTestPred)

print(f"MAE on test data: {testMAE:.2f}")

MAE on test data: 10.50