## Employee Data Using Pandas Selection Techniques
### Tasks to Perform
1. Create a pandas DataFrame using the employee data provided below
2. Select and display only the 'Name', 'Department', and 'Salary' columns
3. Use iloc to display the employee at row position 5
4. Use loc to display the employee with EmployeeID 208
5. Filter and display all employees from the 'Engineering' department
6. Filter and display all employees with Salary greater than 70000
7. Filter and display employees from 'Sales' department with Performance Score >= 4
8. Sort the entire DataFrame by Salary in descending order and display the top 3 highest-paid employees
9. Sort by Department (ascending) and then by Salary (descending) within each department

In [1]:
import pandas as pd

In [36]:
## 1. Create a pandas DataFrame using the employee data provided below
employees = {
    "EmployeeID": [201, 202, 203, 204, 205, 206, 207, 208, 209, 210],
    "Name": ["Sarah", "Michael", "Jennifer", "David", "Lisa", "James", "Emma", "Robert", "Sophia", "William"],
    "Department": ["Engineering", "Sales", "Marketing", "Engineering", "HR", "Sales", "Engineering", "Marketing", "Sales", "HR"],
    "Salary": [85000, 62000, 71000, 92000, 58000, 68000, 78000, 75000, 65000, 60000],
    "Performance Score": [4, 3, 5, 5, 4, 4, 3, 4, 5, 3],
    "Years of Service": [5, 3, 7, 8, 4, 6, 2, 5, 4, 3]
}

empDF = pd.DataFrame(employees,index=employees['EmployeeID'])
empDF

,EmployeeID,Name,Department,Salary,Performance Score,Years of Service
201,201,Sarah,Engineering,85000,4,5
202,202,Michael,Sales,62000,3,3
203,203,Jennifer,Marketing,71000,5,7
204,204,David,Engineering,92000,5,8
205,205,Lisa,HR,58000,4,4
206,206,James,Sales,68000,4,6
207,207,Emma,Engineering,78000,3,2
208,208,Robert,Marketing,75000,4,5
209,209,Sophia,Sales,65000,5,4
210,210,William,HR,60000,3,3

In [20]:
## 2. Select and display only the 'Name', 'Department', and 'Salary' columns
empDF[['Name','Department','Salary']]

         Name   Department  Salary
201     Sarah  Engineering   85000
202   Michael        Sales   62000
203  Jennifer    Marketing   71000
204     David  Engineering   92000
205      Lisa           HR   58000
206     James        Sales   68000
207      Emma  Engineering   78000
208    Robert    Marketing   75000
209    Sophia        Sales   65000
210   William           HR   60000

In [21]:
## 3. Use iloc to display the employee at row position 5
empDF.iloc[5]

EmployeeID             206
Name                 James
Department           Sales
Salary               68000
Performance Score        4
Years of Service         6
Name: 206, dtype: object

In [22]:
## 4.Use loc to display the employee with EmployeeID 208
empDF.loc[208]

EmployeeID                 208
Name                    Robert
Department           Marketing
Salary                   75000
Performance Score            4
Years of Service             5
Name: 208, dtype: object

In [23]:
## 5. Filter and display all employees from the 'Engineering' department
empDF[empDF['Department'] == 'Engineering']

,EmployeeID,Name,Department,Salary,Performance Score,Years of Service
201,201,Sarah,Engineering,85000,4,5
204,204,David,Engineering,92000,5,8
207,207,Emma,Engineering,78000,3,2

In [31]:
## 6. Filter and display all employees with Salary greater than 70000
empDF[empDF['Salary'] > 70000]

,EmployeeID,Name,Department,Salary,Performance Score,Years of Service
201,201,Sarah,Engineering,85000,4,5
203,203,Jennifer,Marketing,71000,5,7
204,204,David,Engineering,92000,5,8
207,207,Emma,Engineering,78000,3,2
208,208,Robert,Marketing,75000,4,5

In [33]:
## 7. Filter and display employees from 'Sales' department with Performance Score >= 4
empDF[(empDF['Department'] == 'Sales') & (empDF['Performance Score'] >= 4)]

,EmployeeID,Name,Department,Salary,Performance Score,Years of Service
206,206,James,Sales,68000,4,6
209,209,Sophia,Sales,65000,5,4

In [34]:
## 8. Sort the entire DataFrame by Salary in descending order and display the top 3 highest-paid employees
empDF.sort_values('Salary',ascending=False).head(3)

,EmployeeID,Name,Department,Salary,Performance Score,Years of Service
204,204,David,Engineering,92000,5,8
201,201,Sarah,Engineering,85000,4,5
207,207,Emma,Engineering,78000,3,2

In [45]:
## Sort by Department (ascending) and then by Salary (descending) within each department
empDF.sort_values(by=['Department','Salary'],ascending=[True,False])

,EmployeeID,Name,Department,Salary,Performance Score,Years of Service
204,204,David,Engineering,92000,5,8
201,201,Sarah,Engineering,85000,4,5
207,207,Emma,Engineering,78000,3,2
210,210,William,HR,60000,3,3
205,205,Lisa,HR,58000,4,4
208,208,Robert,Marketing,75000,4,5
203,203,Jennifer,Marketing,71000,5,7
206,206,James,Sales,68000,4,6
209,209,Sophia,Sales,65000,5,4
202,202,Michael,Sales,62000,3,3